### ISSUE TITLE
16GB vram not enough?

### ISSUE THREAD

**Issue by boogertwilliams** [colinurbs/FramePack-Studio#83]
It works on my 4090, but on my 16GB 4070Ti I get

"CUDA out of memory. Tried to allocate 202.00 MiB. GPU 0 has a total capacity of 15.99 GiB of which 4.93 GiB is free. Of the allocated memory 9.67 GiB is allocated by PyTorch, and 83.47 MiB is reserved by PyTorch but unallocated"

**Comment by Marc0ai** [comment]
I normally use it with 4070 12gb, the problem is not the hardware.
Maybe with 16gb the tool thinks you can use high vram mode and therefore overloads everything.
Then another thing I did was to change these parameters:

text_encoder.to(cpu)
text_encoder_2.to(cpu)
image_encoder.to(gpu)
vae.to(gpu)

I don't know if it actually changes anything, but in theory this way the text encoders work with the CPU and lighten the load (I'm not sure)

**Comment by able2608** [comment]
That's weird. It definitely can run on 16GB of VRAM. I have been using it on 6GB and it is running smoothly. Not pretty sure if installing sageattention and other attention optimization package will help though.

As a side note you might want to crank up the reserved VRAM a bit though leaving it at 6GB should be fine already. Also you might want to check if you are running something else that is also using GPU at the same time.



> I normally use it with 4070 12gb, the problem is not the hardware. Maybe with 16gb the tool thinks you can use high vram mode and therefore overloads everything. Then another thing I did was to change these parameters:
> 
> text_encoder.to(cpu) text_encoder_2.to(cpu) image_encoder.to(gpu) vae.to(gpu)
> 
> I don't know if it actually changes anything, but in theory this way the text encoders work with the CPU and lighten the load (I'm not sure)

As for those changes it means that the text encoders (aka clips for the early days) will probably be run on CPU (I don't know if it will be moved back to cuda by the program somewhere else), which could be quite slow. Not pretty sure how the system handles different VRAM sizes but if you have VRAM I would advice you to not change it to speed up text encode a bit.

**Comment by DirkHeche** [comment]
> It works on my 4090, but on my 16GB 4070Ti I get
> 
> "CUDA out of memory. Tried to allocate 202.00 MiB. GPU 0 has a total capacity of 15.99 GiB of which 4.93 GiB is free. Of the allocated memory 9.67 GiB is allocated by PyTorch, and 83.47 MiB is reserved by PyTorch but unallocated"

In which environment are you running FramePack Studio? I noticed this behaviour on certain gpu types in runpod.io, e. g. (if I remember correctly) Tesla V100. An RTX 3090 is all fine, others show the issue you mentioned.

**Comment by Digioso** [comment]
I have a 5070 TI 16GB and can't use FP Studio because I receive out of memory. I'm using FP Studio within Pinokio.

**Comment by Rkkss** [comment]
what your system RAM?
someone said set virtual ram to 80GB helped

**Comment by Digioso** [comment]
I have 32GB.

**Comment by able2608** [comment]
To increase virtual RAM size, search `Advanced System Settings` in the start menu and open it. Open performance settings (the `settings` button under the `Performance` block, the first one for me) and go to `Advanced`. Click on the `Change` button under the section `Virtual Memory`, deselect `Automatically manage ...` on the top, select `Custom Size` and enter something else. I used 32000 MB initial size and 96000 MB max size for my 16GB RAM setup and it is working for me for now.
Do note that if you have two hard drives with different IO speed, always put the virtual memory AND all the program on the faster one, else the speed will be dog slow as the system fetches whatever is stored on it to the memory. You should be able to observe the speed in the task manager when copying large files.

**Comment by Digioso** [comment]
Thanks! With increasing Virtual Memory to 96GB it also works for me!
